# Generated by Django 5.2.2 on 2025-08-25 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IotDeviceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('password', models.CharField(max_length=510, verbose_name='Passwort')),
                ('status', models.IntegerField(choices=[(0, 'Unbestätigt'), (1, 'Aktiv'), (2, 'Gebannt'), (-1, 'Gelöscht'), (-2, 'Endgültig gelöscht')], default=1, verbose_name='Status')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Startdatum')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Enddatum')),
                ('comment', models.CharField(blank=True, max_length=510, verbose_name='Kommentar')),
                ('mac_address', models.CharField(help_text='Format: AA:BB:CC:DD:EE:FF', max_length=17, unique=True, verbose_name='MAC-Adresse')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_sponsored', to=settings.AUTH_USER_MODEL, verbose_name='Gastgeber:in')),
            ],
            options={
                'verbose_name': 'IoT Device Account',
                'verbose_name_plural': 'IoT Device Accounts',
                'permissions': [('iotdevice_access', 'Can manage IoT device accounts')],
            },
        ),
    ]
