# Generated by Django 5.2.2 on 2025-08-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotdevices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iotdeviceaccount',
            name='comment',
        ),
        migrations.AddField(
            model_name='iotdeviceaccount',
            name='device_name',
            field=models.CharField(blank=True, max_length=510, verbose_name='Gerätename'),
        ),
        migrations.AlterField(
            model_name='iotdeviceaccount',
            name='mac_address',
            field=models.CharField(max_length=17, unique=True, verbose_name='MAC-Adresse'),
        ),
    ]
