# Generated by Django 5.2.2 on 2025-08-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotdevices', '0002_remove_iotdeviceaccount_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iotdeviceaccount',
            name='mac_address',
            field=models.CharField(max_length=17, verbose_name='MAC-Adresse'),
        ),
    ]
