# Generated by Django 5.2.6 on 2025-09-30 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FirewallRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(help_text='UUID der Regel in der OPNsense Firewall', unique=True, verbose_name='Firewall UUID')),
                ('name', models.CharField(help_text='Beschreibender Name für die Firewall-Regel', max_length=100, verbose_name='Regelname')),
                ('description', models.TextField(blank=True, help_text='Detaillierte Beschreibung des Zwecks dieser Regel', verbose_name='Beschreibung')),
                ('is_active', models.BooleanField(default=True, help_text='Regel wird im Frontend angezeigt', verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Firewall-Regel',
                'verbose_name_plural': 'Firewall-Regeln',
                'ordering': ['name'],
                'permissions': [('fwconfig_access', 'Can manage firewall configuration')],
            },
        ),
        migrations.CreateModel(
            name='FirewallRuleChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('enabled', 'eingeschaltet'), ('disabled', 'ausgeschaltet')], max_length=20, verbose_name='Aktion')),
                ('api_success', models.BooleanField(default=False, help_text='Wurde die Änderung erfolgreich an die Firewall übertragen?', verbose_name='API erfolgreich')),
                ('api_message', models.TextField(blank=True, help_text='Antwort oder Fehlermeldung von der Firewall-API', verbose_name='API-Nachricht')),
                ('firewall_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='fwconfig.firewallrule', verbose_name='Firewall-Regel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Firewall-Regel Änderung',
                'verbose_name_plural': 'Firewall-Regel Änderungen',
                'ordering': ['-created_at'],
            },
        ),
    ]
