# Generated by Django 5.2.6 on 2025-09-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwconfig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewallrule',
            name='remote_rule_status',
            field=models.BooleanField(default=False, help_text='Aktueller Status der Regel in der OPNsense Firewall', verbose_name='Remote Status'),
        ),
    ]
