# Generated by Django 5.2.2 on 2025-08-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VlanOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('password', models.CharField(max_length=510, verbose_name='Passwort')),
                ('status', models.IntegerField(choices=[(0, 'Unbestätigt'), (1, 'Aktiv'), (2, 'Gebannt'), (-1, 'Gelöscht'), (-2, 'Endgültig gelöscht')], default=1, verbose_name='Status')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Startdatum')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Enddatum')),
                ('mac_address', models.CharField(max_length=17, verbose_name='MAC-Adresse')),
                ('vlan_id', models.IntegerField(help_text='Die VLAN-ID, die diesem Gerät zugewiesen werden soll.', verbose_name='VLAN-ID')),
                ('comment', models.CharField(blank=True, max_length=510, verbose_name='Kommentar')),
            ],
            options={
                'verbose_name': 'VLAN Override',
                'verbose_name_plural': 'VLAN Overrides',
            },
        ),
    ]
