# Generated by Django 5.2.2 on 2025-08-25 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vlanoverride', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vlanoverride',
            name='password',
        ),
    ]
