# Generated by Django 5.2.7 on 2025-10-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlanoverride', '0002_remove_vlanoverride_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlanoverride',
            name='wifi_username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='WLAN-Benutzername'),
        ),
        migrations.AlterField(
            model_name='vlanoverride',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='MAC-Adresse'),
        ),
    ]
